### ISSUE TITLE
-4/31 | HOME |  ページのタイトルがおかしくなった（画像参照）done

### ISSUE THREAD

**Issue by mihanken** [mihanken/renewal_2049#104]
![image](https://user-images.githubusercontent.com/63392680/115962853-4055c500-a558-11eb-8f87-704257ee19b2.png)
こないだまで大丈夫だった気がするからSEO関連でいじってくれた時に何か変わった？

**Comment by Bunchaca44** [comment]
お、これまずいですね直します

**Comment by Bunchaca44** [comment]
直しました
