### ISSUE TITLE
-4/31 | ABOUT | 4/8タウンニュース記事追加（新規）

### ISSUE THREAD

**Issue by mihanken** [mihanken/renewal_2049#97]
リンク：https://www.townnews.co.jp/0110/amp/2021/04/08/569216.html

**Comment by Bunchaca44** [comment]
これってここに新規でもういっこ並べればいいって感じですか？
![image](https://user-images.githubusercontent.com/48648015/114405648-dba67c00-9be1-11eb-91fd-28c5a6862f2f.png)

**Comment by Bunchaca44** [comment]
ざっくりこんな雰囲気でいかがでしょう
![image](https://user-images.githubusercontent.com/48648015/114406644-ab131200-9be2-11eb-902d-25ef4ad880a7.png)

**Comment by mihanken** [comment]
そんな感じでイメージしていた！！おなしゃす！！

**Comment by Bunchaca44** [comment]
ラジャ

**Comment by mihanken** [comment]
なんかバグってね？

**Comment by Bunchaca44** [comment]
サムネタイトル差し替え忘れてますね直しますごめんなさい

**Comment by Bunchaca44** [comment]
直しました

**Comment by mihanken** [comment]
![image](https://user-images.githubusercontent.com/63392680/115725962-3f3c6080-a3bd-11eb-858e-81b5f60d68a8.png)
表記統一（2021.04.08）おなしゃす！

**Comment by Bunchaca44** [comment]
修正しました
