### ISSUE TITLE
-4/31 | ABOUT | 団体情報が古いので更新

### ISSUE THREAD

**Issue by mihanken** [mihanken/renewal_2049#98]
以下に差し替え

三浦半島研究会は、2018年度横浜市立大学公認サークルとして発足されました。

その後実績が認められ、2020年度には正式な文化系部活動へと昇格を果たしました。

「三浦半島ジャーナル」の発刊をメインの活動とし、現在まで計7号発行しています。

現在約50名で運営され、三浦半島内でさまざまなクリエイティブを制作するほか、

三浦半島を盛り上げるためのやイベント開催なども手がけています。

**Comment by Bunchaca44** [comment]
done
